version: "3.8"

services:
  agent:
    build: .
    container_name: ferrolink-agent
    environment:
      - RUST_LOG=info
    volumes:
      - ./uploads:/app/uploads
      - ./cert.pem:/app/cert.pem:ro
      - ./key.pem:/app/key.pem:ro
    ports:
      - "8080:8080"  # TLS agent port
      - "9090:9090"  # Prometheus metrics

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - agent 

  # --- one-shot migration runner -----------------------------------
  migrate:
    image: launchbadge/sqlx-cli:0.7.2
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations:ro
    environment:
      - DATABASE_URL=postgres://ferrolink:ferrolink@postgres:5432/ferrolink
    command: ["sqlx", "migrate", "run", "--source", "/migrations"]

  # --- React dashboard ---------------------------------------------
  dashboard:
    build: ./dashboard
    ports:
      - "3000:80"      # served via nginx inside image
    depends_on:
      - agent
    environment:
      - VITE_API_BASE=http://localhost:9090

  postgres:
    image: postgres:15-alpine
    container_name: ferrolink-postgres
    restart: unless-stopped
    environment:
      # TODO: move to secrets.env
      POSTGRES_USER: ferrolink
      POSTGRES_PASSWORD: ferrolink
      POSTGRES_DB: ferrolink
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: 